@echo off
echo Starting FB_APU01 with .env.FB_APU01...
echo Forcing rebuild of API to ensure latest code changes...
docker compose --env-file .env.FB_APU01 build --no-cache api
docker compose --env-file .env.FB_APU01 up -d

echo.
echo Containers started. Attaching to backend logs (Service: api)...
docker compose --env-file .env.FB_APU01 logs -f api